/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_andresmoncada;

import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Dell
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tree2 = new javax.swing.JTree();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        prom = new javax.swing.JMenuItem();
        asc = new javax.swing.JMenuItem();
        camb = new javax.swing.JMenuItem();
        desp = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        msg = new javax.swing.JMenuItem();
        mcst = new javax.swing.JMenuItem();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree_add = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        label_add = new javax.swing.JLabel();
        add_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        add_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        add_sal = new javax.swing.JTextField();
        add_pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        add_inst = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jDialog1WindowClosed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Gerente");
        tree2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tree2);

        jLabel5.setText("Clic derecho");

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        prom.setText("Promover Empleado");
        prom.setToolTipText("");
        prom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promActionPerformed(evt);
            }
        });
        jPopupMenu1.add(prom);

        asc.setText("Ascender Empleado");
        jPopupMenu1.add(asc);

        camb.setText("Cambiar puesto");
        jPopupMenu1.add(camb);

        desp.setText("Despedir");
        jPopupMenu1.add(desp);
        jPopupMenu1.add(jSeparator1);

        msg.setText("Enviar Mensaje");
        jPopupMenu1.add(msg);

        mcst.setText("Enviar multicast");
        jPopupMenu1.add(mcst);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Gerente");
        tree_add.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(tree_add);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_add.setText("Agregar Gerente General");

        jLabel2.setText("Nombre");

        jLabel3.setText("ID");

        jLabel4.setText("Salario");

        jLabel1.setText("Contraseña");

        add_inst.setForeground(new java.awt.Color(100, 100, 100));

        jButton2.setText("Empleados agregados");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_inst)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(add_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                        .addComponent(add_sal)
                                        .addComponent(add_nombre)
                                        .addComponent(add_id))))
                            .addComponent(label_add, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_add)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(add_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add_inst)
                                .addGap(7, 7, 7)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTreeModel tm = (DefaultTreeModel)tree_add.getModel();
        if(!g){
            try{
                tm.setRoot(new DefaultMutableTreeNode(
                new Empleado(add_nombre.getText(),Integer.parseInt(add_id.getText()),add_pass.getText(),null,Integer.parseInt(add_sal.getText()),"Gerente general")));
                label_add.setText("Agregar Empleado/Subgerente");
                add_nombre.setText("");
                add_id.setText("");
                add_sal.setText("");
                add_pass.setText("");
                jButton2.setEnabled(true);
                add_inst.setText("Para agregar un empleado seleccione su jefe primero");
                g = true;
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Ocurrio un error al agregar al gerente");
            }
            tm.reload();
        }//no hay gerente general
        else if(tree_add.getSelectionCount() > 0){
            Empleado e = new Empleado(add_nombre.getText(),Integer.parseInt(add_id.getText()),add_pass.getText(),
                    (Empleado)((DefaultMutableTreeNode)tree_add.getSelectionPath().getLastPathComponent()).getUserObject(),Integer.parseInt(add_sal.getText()),"Empleado de primera linea");
            DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(e);
            ((Empleado)((DefaultMutableTreeNode)tree_add.getSelectionPath().getLastPathComponent()).getUserObject()).addEmpleados(e);
            ((DefaultMutableTreeNode)tree_add.getSelectionPath().getLastPathComponent()).add(nodo);
            add_nombre.setText("");
            add_id.setText("");
            add_sal.setText("");
            add_pass.setText("");
            tm.reload();
        }//se selecciono en el arbol
        else{
            JOptionPane.showMessageDialog(this, "Seleccione a un gerente primero");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton1.setEnabled(false);
        jDialog1.setModal(true);
        jDialog1.setLocationRelativeTo(this);
        jDialog1.pack();
        tree2.setModel((DefaultTreeModel)tree_add.getModel());
        jButton2.setEnabled(false);
        hide();
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tree2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree2MouseClicked
        if(evt.isMetaDown()){
            int row = tree2.getClosestRowForLocation(evt.getX(), evt.getY());
            tree2.setSelectionRow(row);
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tree2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jDialog1.dispose();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void promActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promActionPerformed
        DefaultTreeModel tm = (DefaultTreeModel) tree2.getModel();
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) tree2.getSelectionPath().getLastPathComponent();
        if(!nodo.equals((DefaultMutableTreeNode)tm.getRoot())){
            if(!nodo.getParent().equals(tm.getRoot())){
                DefaultMutableTreeNode padre = (DefaultMutableTreeNode) nodo.getParent();
                tm.removeNodeFromParent(nodo);
                ((DefaultMutableTreeNode)padre.getParent()).add(nodo);
                tm.reload();
            }else{
                JOptionPane.showMessageDialog(tree2, "No se puede promover");
            }
        }else
            JOptionPane.showMessageDialog(tree2, "No se puede promover");
    }//GEN-LAST:event_promActionPerformed

    private void jDialog1WindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowClosed
        jDialog1.dispose();
        dispose();
    }//GEN-LAST:event_jDialog1WindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add_id;
    private javax.swing.JLabel add_inst;
    private javax.swing.JTextField add_nombre;
    private javax.swing.JPasswordField add_pass;
    private javax.swing.JTextField add_sal;
    private javax.swing.JMenuItem asc;
    private javax.swing.JMenuItem camb;
    private javax.swing.JMenuItem desp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel label_add;
    private javax.swing.JMenuItem mcst;
    private javax.swing.JMenuItem msg;
    private javax.swing.JMenuItem prom;
    private javax.swing.JTree tree2;
    private javax.swing.JTree tree_add;
    // End of variables declaration//GEN-END:variables
    private boolean g = false;
    Para_el_archivo pa = new Para_el_archivo("./Mensajes.lab");
}
